%% test_clinical_consistency_target_tiers.m
% =========================================================================
% Regression checks for clinical consistency audit and target-tier RMSE.
%
% AUTHOR:   Unified VSD Model
% DATE:     2026-05-14
% VERSION:  1.0
% =========================================================================

clear; clc;
root = fileparts(mfilename('fullpath'));
project_root = fullfile(root, '..');
addpath(genpath(project_root));

fprintf('==========================================\n');
fprintf('  UNIFIED VSD MODEL - Target Governance Test\n');
fprintf('==========================================\n\n');

clinical = patient_reyna();
scenario = 'pre_surgery';
audit = audit_clinical_consistency(clinical, scenario);
tiers = build_target_tiers(clinical, scenario, audit);

assert(abs(audit.SV_Qs - clinical.pre_surgery.CO_Lmin * 1000 / clinical.common.HR) < 1e-10, ...
    'SV_Qs calculation mismatch.');
assert(abs(audit.SV_Qp - clinical.pre_surgery.CO_Lmin * clinical.pre_surgery.QpQs * 1000 / clinical.common.HR) < 1e-10, ...
    'SV_Qp calculation mismatch.');
assert(strcmp(audit.severity, 'critical'), ...
    'Reyna stroke-volume inconsistency should be critical.');
assert(ismember('RVEDV', tiers.consistency_only), ...
    'RVEDV must be downgraded to consistency-check-only for Reyna.');
assert(~ismember('RVEDV', tiers.included_in_calibration), ...
    'RVEDV must not be included in calibration targets when flagged.');
assert(~ismember('RVEDV', tiers.included_in_primary_rmse), ...
    'RVEDV must not be included in governed primary RMSE when flagged.');
assert(ismember('LVEDV', tiers.consistency_only), ...
    'LVEDV must be downgraded to consistency-check-only for Reyna when LV stroke volume conflicts.');
assert(ismember('LVESV', tiers.consistency_only), ...
    'LVESV must be downgraded to consistency-check-only for Reyna when LV stroke volume conflicts.');
assert(~ismember('LVEDV', tiers.included_in_calibration), ...
    'LVEDV must not be included in calibration targets when flagged.');
assert(~ismember('LVESV', tiers.included_in_calibration), ...
    'LVESV must not be included in calibration targets when flagged.');
assert(~ismember('LVEDV', tiers.included_in_primary_rmse), ...
    'LVEDV must not be included in governed primary RMSE when flagged.');
assert(~ismember('LVESV', tiers.included_in_primary_rmse), ...
    'LVESV must not be included in governed primary RMSE when flagged.');
assert(ismember('LVEF', tiers.consistency_only), ...
    'EF/LVEF must be consistency-check-only when LVEDV and LVESV are already available.');
assert(~ismember('LVEF', tiers.included_in_calibration), ...
    'Derived EF must not be independently fitted with its source volumes.');
svr_tier_idx = find(strcmp(tiers.table.Metric, 'SVR'), 1, 'first');
assert(~isempty(svr_tier_idx) && strcmp(tiers.table.Tier{svr_tier_idx}, 'derived_validation'), ...
    'SVR must be retained as a derived validation metric.');
assert(~ismember('SVR', tiers.included_in_calibration), ...
    'Derived SVR must not be included in calibration targets.');
assert(~ismember('SVR', tiers.included_in_primary_rmse), ...
    'Derived SVR must not be included in governed primary RMSE.');
pvr_tier_idx = find(strcmp(tiers.table.Metric, 'PVR'), 1, 'first');
assert(~isempty(pvr_tier_idx) && strcmp(tiers.table.Tier{pvr_tier_idx}, 'derived_validation'), ...
    'Derived PVR must be retained as a derived validation metric when source fields are available.');
assert(~ismember('PVR', tiers.included_in_calibration), ...
    'Derived PVR must not be included in calibration targets.');
assert(~ismember('PVR', tiers.included_in_primary_rmse), ...
    'Derived PVR must not be included in governed primary RMSE.');

targets = get_calibration_targets(scenario, clinical);
pvr_target_idx = find(strcmp({targets.Metric}, 'PVR'), 1, 'first');
expected_pvr = (clinical.pre_surgery.PAP_mean_mmHg - clinical.pre_surgery.LAP_mean_mmHg) / ...
    (clinical.pre_surgery.CO_Lmin * clinical.pre_surgery.QpQs);
assert(~isempty(pvr_target_idx) && abs(targets(pvr_target_idx).ClinicalValue - expected_pvr) < 1e-10, ...
    'PVR should be derived from available clinical PAP, LAP, CO, and Qp/Qs.');
metrics = struct();
for idx = 1:numel(targets)
    if isfinite(targets(idx).ClinicalValue)
        metrics.(targets(idx).Metric) = targets(idx).ClinicalValue;
    end
end
metrics.RVEDV = clinical.pre_surgery.RVEDV_mL * 2;

report = validation_report(clinical, metrics, metrics, scenario, ...
    'PrimaryMetrics', {'CO_Lmin','QpQs','PAP_mean','SAP_mean','RAP_mean'}, ...
    'TargetTiers', tiers, ...
    'ClinicalConsistencyAudit', audit);

assert(report.rmse_full_cal > 0, ...
    'Full RMSE must include the deliberately perturbed RVEDV.');
assert(report.rmse_primary_cal < 1e-12, ...
    'Primary RMSE must exclude deliberately perturbed consistency-only targets.');
assert(isfield(report, 'clinical_data_rank') && ~isempty(report.clinical_data_rank), ...
    'Validation report must expose clinical data availability ranking.');
assert(any((strcmp(report.clinical_data_rank.Field, 'EF') | ...
    strcmp(report.clinical_data_rank.Field, 'LVEF')) & ...
    strcmp(report.clinical_data_rank.EvidenceClass, 'directly_derived')), ...
    'EF/LVEF should be ranked as directly derived clinical evidence.');

clinical_razka = patient_profile_Razka();
tiers_razka = build_target_tiers(clinical_razka, scenario);
lvedp_tier_idx = find(strcmp(tiers_razka.table.Metric, 'LVEDP'), 1, 'first');
rvedp_tier_idx = find(strcmp(tiers_razka.table.Metric, 'RVEDP'), 1, 'first');
assert(~isempty(lvedp_tier_idx) && strcmp(tiers_razka.table.Tier{lvedp_tier_idx}, 'validation_holdout'), ...
    'Sparse LVEDP without LV volume anchors must be validation holdout.');
assert(~isempty(rvedp_tier_idx) && strcmp(tiers_razka.table.Tier{rvedp_tier_idx}, 'validation_holdout'), ...
    'Sparse RVEDP without RV volume anchors must be validation holdout.');
assert(~ismember('LVEDP', tiers_razka.included_in_primary_rmse) && ...
    ~ismember('RVEDP', tiers_razka.included_in_primary_rmse), ...
    'Sparse EDP holdouts must not inflate governed primary RMSE.');

fprintf('\n[PASS] Clinical audit, target tiers, and RMSE masks behave as expected.\n');
