function provenance = build_baseline_provenance(params_ref)
% BUILD_BASELINE_PROVENANCE
% -----------------------------------------------------------------------
% Builds an explicit provenance table for the hybrid adult baseline used
% by the Unified VSD model. The table records which defaults come directly
% from Bozkurt-style adult physiology, which arise from the Valenti
% circulation architecture, and which were later consistency corrections.
%
% INPUTS:
%   params_ref   - baseline parameter struct from default_parameters      [-]
%
% OUTPUTS:
%   provenance   - table describing baseline source lineage              [-]
%
% NOTES:
%   - This is a scientific-audit helper, not a calibration routine.
%   - The current repo uses a hybrid foundation: Bozkurt-like chamber and
%     vascular magnitudes inside a Valenti-style 14-state circulation.
%
% REFERENCES:
%   [1] Bozkurt S. PLoS ONE 2019;14(10):e0224663.
%   [2] Valenti (2023). Full-order 0D cardiovascular model.
%
% AUTHOR:   Unified VSD Model
% DATE:     2026-05-08
% VERSION:  1.0
% -----------------------------------------------------------------------

if nargin < 1 || isempty(params_ref)
    params_ref = default_parameters();
end

rows = {};

rows(end+1, :) = make_row(params_ref, 'HR', 'timing', 'bpm', ...
    'bozkurt2019_adult_foundation', 'generic adult baseline', 'high', ...
    'Adult resting heart rate used as the pre-scaling reference.');

rows(end+1, :) = make_row(params_ref, 'V0.RA', 'chamber_v0', 'mL', ...
    'bozkurt2019_table1', 'adult chamber baseline', 'high', ...
    'Adult right-atrial unstressed volume.');
rows(end+1, :) = make_row(params_ref, 'V0.RV', 'chamber_v0', 'mL', ...
    'bozkurt2019_table1', 'adult chamber baseline', 'high', ...
    'Adult right-ventricular unstressed volume.');
rows(end+1, :) = make_row(params_ref, 'V0.LA', 'chamber_v0', 'mL', ...
    'bozkurt2019_table1', 'adult chamber baseline', 'high', ...
    'Adult left-atrial unstressed volume.');
rows(end+1, :) = make_row(params_ref, 'V0.LV', 'chamber_v0', 'mL', ...
    'bozkurt2019_table1', 'adult chamber baseline', 'high', ...
    'Adult left-ventricular unstressed volume.');

rows(end+1, :) = make_row(params_ref, 'E.LV.EA', 'elastance', 'mmHg/mL', ...
    'hybrid_bozkurt_es_and_local_decomposition', 'adult chamber baseline', 'medium', ...
    'Derived from adult LV systolic elastance with active-passive decomposition for the current formulation.');
rows(end+1, :) = make_row(params_ref, 'E.LV.EB', 'elastance', 'mmHg/mL', ...
    'derived_from_ed_pressure_volume_anchor', 'architecture-specific derivation', 'medium', ...
    'Computed from adult LV end-diastolic pressure-volume anchor.');
rows(end+1, :) = make_row(params_ref, 'E.RV.EA', 'elastance', 'mmHg/mL', ...
    'hybrid_bozkurt_es_and_local_decomposition', 'adult chamber baseline', 'medium', ...
    'Derived from adult RV systolic elastance with active-passive decomposition.');
rows(end+1, :) = make_row(params_ref, 'E.RV.EB', 'elastance', 'mmHg/mL', ...
    'derived_from_ed_pressure_volume_anchor', 'architecture-specific derivation', 'medium', ...
    'Computed from adult RV end-diastolic pressure-volume anchor.');
rows(end+1, :) = make_row(params_ref, 'E.LA.EA', 'elastance', 'mmHg/mL', ...
    'bozkurt2019_table1', 'adult chamber baseline', 'high', ...
    'Adult left-atrial active elastance component.');
rows(end+1, :) = make_row(params_ref, 'E.LA.EB', 'elastance', 'mmHg/mL', ...
    'bozkurt2019_table1', 'adult chamber baseline', 'high', ...
    'Adult left-atrial minimum elastance component.');
rows(end+1, :) = make_row(params_ref, 'E.RA.EA', 'elastance', 'mmHg/mL', ...
    'bozkurt2019_table1', 'adult chamber baseline', 'high', ...
    'Adult right-atrial active elastance component.');
rows(end+1, :) = make_row(params_ref, 'E.RA.EB', 'elastance', 'mmHg/mL', ...
    'bozkurt2019_table1', 'adult chamber baseline', 'high', ...
    'Adult right-atrial minimum elastance component.');

rows(end+1, :) = make_row(params_ref, 'R.SAR', 'systemic_vascular', 'mmHg*s/mL', ...
    'bozkurt2019_table2', 'adult vascular baseline', 'high', ...
    'Adult proximal systemic arterial resistance.');
rows(end+1, :) = make_row(params_ref, 'C.SAR', 'systemic_vascular', 'mL/mmHg', ...
    'local_consistency_correction_from_bozkurt_foundation', 'local tuning correction', 'medium', ...
    'Raised from the Bozkurt adult magnitude to maintain pulse pressure and arterial volume consistency in this architecture.');
rows(end+1, :) = make_row(params_ref, 'L.SAR', 'systemic_vascular', 'mmHg*s^2/mL', ...
    'valenti2023_architecture_placeholder', 'architecture-specific derivation', 'low', ...
    'Small inertance placeholder carried by the Valenti-style flow state.');
rows(end+1, :) = make_row(params_ref, 'R.SC', 'systemic_vascular', 'mmHg*s/mL', ...
    'local_split_of_bozkurt_systemic_afterload', 'architecture-specific derivation', 'medium', ...
    'Systemic afterload is split across arterial and capillary/systemic-control blocks in the 14-state architecture.');
rows(end+1, :) = make_row(params_ref, 'C.SC', 'systemic_vascular', 'mL/mmHg', ...
    'local_split_of_systemic_compliance', 'architecture-specific derivation', 'medium', ...
    'Systemic compliance is distributed across SAR and SC blocks in the current model.');
rows(end+1, :) = make_row(params_ref, 'R.SVEN', 'systemic_vascular', 'mmHg*s/mL', ...
    'bozkurt2019_table2', 'adult vascular baseline', 'high', ...
    'Adult systemic venous resistance.');
rows(end+1, :) = make_row(params_ref, 'C.SVEN', 'systemic_vascular', 'mL/mmHg', ...
    'bozkurt2019_table2', 'adult vascular baseline', 'high', ...
    'Adult systemic venous compliance.');
rows(end+1, :) = make_row(params_ref, 'L.SVEN', 'systemic_vascular', 'mmHg*s^2/mL', ...
    'valenti2023_architecture_placeholder', 'architecture-specific derivation', 'low', ...
    'Small inertance placeholder for the venous flow state.');
rows(end+1, :) = make_row(params_ref, 'V0.SAR', 'vascular_v0', 'mL', ...
    'derived_from_current_C_and_nominal_pressure', 'architecture-specific derivation', 'medium', ...
    'Computed from current arterial compliance and nominal adult arterial pressure.');
rows(end+1, :) = make_row(params_ref, 'V0.SC', 'vascular_v0', 'mL', ...
    'derived_from_current_C_and_nominal_pressure', 'architecture-specific derivation', 'medium', ...
    'Computed from current systemic-capillary compliance and nominal pressure.');
rows(end+1, :) = make_row(params_ref, 'V0.SVEN', 'vascular_v0', 'mL', ...
    'derived_from_current_C_and_nominal_pressure', 'architecture-specific derivation', 'medium', ...
    'Computed from current systemic venous compliance and nominal venous pressure.');

rows(end+1, :) = make_row(params_ref, 'R.PAR', 'pulmonary_vascular', 'mmHg*s/mL', ...
    'bozkurt2019_table2', 'adult vascular baseline', 'high', ...
    'Adult proximal pulmonary arterial resistance.');
rows(end+1, :) = make_row(params_ref, 'C.PAR', 'pulmonary_vascular', 'mL/mmHg', ...
    'bozkurt2019_table2', 'adult vascular baseline', 'high', ...
    'Adult proximal pulmonary arterial compliance.');
rows(end+1, :) = make_row(params_ref, 'L.PAR', 'pulmonary_vascular', 'mmHg*s^2/mL', ...
    'valenti2023_architecture_placeholder', 'architecture-specific derivation', 'low', ...
    'Small inertance placeholder for the pulmonary arterial flow state.');
rows(end+1, :) = make_row(params_ref, 'R.PCOX', 'pulmonary_capillary_split', 'mmHg*s/mL', ...
    'valenti2023_parallel_capillary_split', 'architecture-specific derivation', 'medium', ...
    'Pulmonary capillary branch resistance from the Valenti-style parallel split.');
rows(end+1, :) = make_row(params_ref, 'C.PCOX', 'pulmonary_capillary_split', 'mL/mmHg', ...
    'valenti2023_parallel_capillary_split', 'architecture-specific derivation', 'medium', ...
    'Pulmonary capillary branch compliance from the current parallel representation.');
rows(end+1, :) = make_row(params_ref, 'R.PCNO', 'pulmonary_capillary_split', 'mmHg*s/mL', ...
    'valenti2023_parallel_capillary_split', 'architecture-specific derivation', 'medium', ...
    'Pulmonary capillary non-oxygenated branch resistance placeholder preserving the branch ratio.');
rows(end+1, :) = make_row(params_ref, 'C.PCNO', 'pulmonary_capillary_split', 'mL/mmHg', ...
    'valenti2023_parallel_capillary_split', 'architecture-specific derivation', 'medium', ...
    'Pulmonary capillary non-oxygenated branch compliance placeholder preserving total capillary compliance.');
rows(end+1, :) = make_row(params_ref, 'R.PVEN', 'pulmonary_vascular', 'mmHg*s/mL', ...
    'local_consistency_correction_from_bozkurt_foundation', 'local tuning correction', 'medium', ...
    'Pulmonary venous resistance adjusted for the current 14-state architecture.');
rows(end+1, :) = make_row(params_ref, 'C.PVEN', 'pulmonary_vascular', 'mL/mmHg', ...
    'derived_from_nominal_volume_over_pressure', 'architecture-specific derivation', 'medium', ...
    'Pulmonary venous compliance derived from nominal adult venous volume over pressure.');
rows(end+1, :) = make_row(params_ref, 'V0.PAR', 'vascular_v0', 'mL', ...
    'derived_from_current_C_and_nominal_pressure', 'architecture-specific derivation', 'medium', ...
    'Computed from current pulmonary arterial compliance and nominal pressure.');
rows(end+1, :) = make_row(params_ref, 'V0.PCOX', 'vascular_v0', 'mL', ...
    'pressure_state_placeholder', 'architecture-specific derivation', 'low', ...
    'Capillary branch uses a pressure-state formulation, so V0 is a placeholder.');
rows(end+1, :) = make_row(params_ref, 'V0.PCNO', 'vascular_v0', 'mL', ...
    'pressure_state_placeholder', 'architecture-specific derivation', 'low', ...
    'Capillary branch uses a pressure-state formulation, so V0 is a placeholder.');
rows(end+1, :) = make_row(params_ref, 'V0.PVEN', 'vascular_v0', 'mL', ...
    'derived_from_nominal_volume_over_pressure', 'architecture-specific derivation', 'medium', ...
    'Pulmonary venous unstressed volume from nominal adult venous pressure-volume balance.');

rows(end+1, :) = make_row(params_ref, 'R.vsd', 'shunt_reference', 'mmHg*s/mL', ...
    'closed_shunt_numerical_reference', 'scenario sentinel', 'high', ...
    'Healthy adult reference uses a numerically closed VSD rather than a physiologic defect.');

provenance = cell2table(rows, 'VariableNames', { ...
    'Parameter', 'Group', 'Unit', 'CurrentValue', 'FoundationSource', ...
    'EvidenceScope', 'ConfidenceLevel', 'Notes'});
end

function row = make_row(params_ref, name, group_name, unit_name, source_name, scope_name, confidence_name, note_text)
row = { ...
    name, ...
    group_name, ...
    unit_name, ...
    get_nested_value(params_ref, name), ...
    source_name, ...
    scope_name, ...
    confidence_name, ...
    note_text};
end

function value = get_nested_value(params_ref, dotted_name)
parts = strsplit(dotted_name, '.');
value = params_ref;
for idx = 1:numel(parts)
    part = parts{idx};
    if isstruct(value) && isfield(value, part)
        value = value.(part);
    else
        error('build_baseline_provenance:missingField', ...
            'Unable to resolve parameter path %s.', dotted_name);
    end
end
end
