function registry = scaling_method_registry()
% SCALING_METHOD_REGISTRY
% -----------------------------------------------------------------------
% Central provenance registry for supported pediatric scaling methods.
% This records what the code implements, not only what papers are cited.
% -----------------------------------------------------------------------

registry = struct();

registry.zhang = struct( ...
    'ScalingMode', 'zhang', ...
    'DefaultPublicationRole', 'primary_prior', ...
    'DefaultExploratoryRole', 'exploratory', ...
    'CitationLabel', 'Zhang et al. 2019', ...
    'DOI', '10.1016/j.compbiomed.2019.03.021', ...
    'PMID', '31005012', ...
    'ImplementationVariant', 'zhang_weight_allometry_plus_project_extensions', ...
    'DeviationFromCitation', ['Project-adapted VSD disease seeding; ' ...
        'blood-volume reconciliation; target governance; maturation layer; ' ...
        'inertance scaling borrowed from Lundquist-style mechanical similarity.'], ...
    'PrimaryRationale', ['Primary publication prior because Zhang et al. ' ...
        'directly targets pediatric age-related cardiovascular allometry for ' ...
        'infants, children, and adolescents.']);

registry.lundquist_bsa = struct( ...
    'ScalingMode', 'lundquist_bsa', ...
    'DefaultPublicationRole', 'comparator', ...
    'DefaultExploratoryRole', 'exploratory', ...
    'CitationLabel', 'Lundquist et al. 2025', ...
    'DOI', '10.1097/MAT.0000000000002528', ...
    'PMID', '', ...
    'ImplementationVariant', 'bsa_only_simplified_lundquist', ...
    'DeviationFromCitation', ['Current code applies a simplified BSA-only ' ...
        'variant and does not implement the full age/sex/growth-chart scaling ' ...
        'reported by Lundquist et al.'], ...
    'PrimaryRationale', ['Comparator/sensitivity method unless explicitly ' ...
        'overridden because the current implementation is not the full ' ...
        'published Lundquist method.']);

end

