function provenance_file = write_scaling_method_provenance(out_dir, policy, baseline_gate_status)
% WRITE_SCALING_METHOD_PROVENANCE  Export scaling citation/provenance table.

if nargin < 3 || isempty(baseline_gate_status)
    baseline_gate_status = get_policy_field(policy, 'BaselineGateStatus', 'not_evaluated');
end
if ~exist(out_dir, 'dir')
    mkdir(out_dir);
end

row = table( ...
    string(get_policy_field(policy, 'ScalingMode', 'unknown')), ...
    string(get_policy_field(policy, 'ScalingRole', 'unknown')), ...
    string(get_policy_field(policy, 'CitationLabel', '')), ...
    string(get_policy_field(policy, 'DOI', '')), ...
    string(get_policy_field(policy, 'PMID', '')), ...
    string(get_policy_field(policy, 'ImplementationVariant', '')), ...
    string(get_policy_field(policy, 'DeviationFromCitation', '')), ...
    string(get_policy_field(policy, 'PrimaryRationale', '')), ...
    string(baseline_gate_status), ...
    'VariableNames', {'ScalingMode','ScalingRole','CitationLabel','DOI','PMID', ...
    'ImplementationVariant','DeviationFromCitation','ReasonForPrimaryOrComparatorRole', ...
    'BaselineGateStatus'});

provenance_file = fullfile(out_dir, 'scaling_method_provenance.csv');
writetable(row, provenance_file);
end

function value = get_policy_field(policy, field_name, fallback)
if isstruct(policy) && isfield(policy, field_name) && ~isempty(policy.(field_name))
    value = policy.(field_name);
else
    value = fallback;
end
end

